### ISSUE TITLE
XEP-0272: Multiparty Jingle (Muji)

### ISSUE THREAD

**Issue by Neustradamus** [valeriansaliou/giggle#90]
There is an update but not official and lost on the Web.
It will be possible to have this version and to send the new version "0.2" to XSF Inbox to be good?
https://xmpp.org/extensions/xep-0272.html

On https://github.com/jappix/jappix/issues/479:
valeriansaliou commented on 24 Jun 2014:
"All done for Muji. I rewrote thecurrent Muji XEP (XEP-0272), based on my implementation experience, feedback & requirements.

Now pending for XSF validation: https://demo.frenchtouch.pro/valerian.saliou/xmpp/extensions/xep-0272.html"

Linked to https://github.com/jappix/jappix/issues/588.

**Comment by Neustradamus** [comment]
One year after, I always search the 2014 version of this XEP-0272 by @valeriansaliou.

**Comment by Neustradamus** [comment]
More two year after, I always search the 2014 version of this XEP-0272 by @valeriansaliou.

**Comment by valeriansaliou** [comment]
I don't have this anymore, consider this closed. Not active anymore on this and no backup of this work.

**Comment by Neustradamus** [comment]
@mar-v-in: For info, there were modifications in Jappix and Giggle.
